select * from customer limit 20;

--1.Total Revenue generated by male and female customers

select gender,sum(purchase_amount) as TotalRevenue
from customer
group by gender;

--2.Customers who used the discount but still spent more than the average purchase amount
select customer_id,discount_applied,purchase_amount
from customer
where discount_applied='Yes' and purchase_amount >= (select avg(purchase_amount) from customer)

--3. Top 5 products with the highest average review rating

select item_purchased , Round(avg(review_rating::numeric),2) as "Average review rating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;

--4. Comparing the average purchase amounts between standard and Express shipping

select shipping_type, Round(avg(purchase_amount),2) as "Average Purchase Amount"
from customer
where shipping_type in ('Express','Standard')
group by shipping_type

--5. Do subscribed customers spend more? compare average spend and total revenue between subscribers and non-subscribers

select subscription_status,round(avg(purchase_amount),2) as "average_spend",
sum(purchase_amount) as "revenue"
from customer
group by subscription_status
order by revenue,average_spend desc


--6. Which 5 products have the highest percentage of purchases with discounts applied
select item_purchased ,Round(100 * sum(Case when discount_applied='Yes' then 1 else 0 end)/ count(*),2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5

--7. Segment Customers into New, Returning and Loyal based on their total
--number of previous purchases, show the count of each segment.

with customer_type as
(
select (case 
when previous_purchases=1 then 'New' 
when  previous_purchases between 2 and 10 then 'Returning' 
else 'Loyal' end) as "cust_types"
from customer
)
select cust_types, count(cust_types)as count
from customer_type
group by cust_types


--8. What are the top 3 most purchased products within each category

with item_counts as (
select category,
item_purchased,
count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id) desc) as item_rank
from customer
group by category, item_purchased
)
select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank<=3;

--9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

select subscription_status,
count(customer_id) as repeat_buyers
from customer 
where previous_purchases>5
group by subscription_status

--10. revenue contribution of each age group?
select age_group, sum(purchase_amount) as "revenue"
from customer
group by age_group
order by revenue desc





